name: DevSecOps Security Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  sast:
    name: Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: python -m pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config p/python src/

  sca:
    name: Trivy SCA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

  container:
    name: Trivy Container Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devsecops-demo:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devsecops-demo:latest
          scan-type: image
          severity: HIGH,CRITICAL
          exit-code: 1